version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: bash -c "while true; do echo hello; sleep 2; done"
    # env_file:
      # - ./.env
    # volumes:
      # - .:/app
