version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - ${CREDENTIALS_FOLDER_PATH}:/data/credentials
